/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OfferRouteImport } from './routes/offer'
import { Route as SafetyRouteImport } from './routes/safety'
import { Route as SearchRouteImport } from './routes/search'
import { Route as RideRideIdRouteImport } from './routes/ride.$rideId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OfferRoute = OfferRouteImport.update({
  id: '/offer',
  path: '/offer',
  getParentRoute: () => rootRouteImport,
} as any)
const SafetyRoute = SafetyRouteImport.update({
  id: '/safety',
  path: '/safety',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const RideRideIdRoute = RideRideIdRouteImport.update({
  id: '/ride/$rideId',
  path: '/ride/$rideId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/offer': typeof OfferRoute
  '/safety': typeof SafetyRoute
  '/search': typeof SearchRoute
  '/ride/$rideId': typeof RideRideIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/offer': typeof OfferRoute
  '/safety': typeof SafetyRoute
  '/search': typeof SearchRoute
  '/ride/$rideId': typeof RideRideIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/offer': typeof OfferRoute
  '/safety': typeof SafetyRoute
  '/search': typeof SearchRoute
  '/ride/$rideId': typeof RideRideIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/offer' | '/safety' | '/search' | '/ride/$rideId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/offer' | '/safety' | '/search' | '/ride/$rideId'
  id: '__root__' | '/' | '/offer' | '/safety' | '/search' | '/ride/$rideId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  OfferRoute: typeof OfferRoute
  SafetyRoute: typeof SafetyRoute
  SearchRoute: typeof SearchRoute
  RideRideIdRoute: typeof RideRideIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offer': {
      id: '/offer'
      path: '/offer'
      fullPath: '/offer'
      preLoaderRoute: typeof OfferRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/safety': {
      id: '/safety'
      path: '/safety'
      fullPath: '/safety'
      preLoaderRoute: typeof SafetyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ride/$rideId': {
      id: '/ride/$rideId'
      path: '/ride/$rideId'
      fullPath: '/ride/$rideId'
      preLoaderRoute: typeof RideRideIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  OfferRoute: OfferRoute,
  SafetyRoute: SafetyRoute,
  SearchRoute: SearchRoute,
  RideRideIdRoute: RideRideIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
